name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        # Fix line endings and permissions
        tr -d '\r' < ~/.ssh/deploy_key > ~/.ssh/deploy_key_unix
        mv ~/.ssh/deploy_key_unix ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan 138.197.174.176 >> ~/.ssh/known_hosts

    - name: Test Connection
      run: ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@138.197.174.176 "echo 'Connected successfully!'"

    - name: Deploy
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@138.197.174.176 '
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          source "$NVM_DIR/bash_completion"
    
          cd /root/finalfront
          git pull origin main
          yarn --frozen-lockfile
          yarn build
          pm2 restart finalfront
    
          echo "✅ Deployment completed!"
        '
